config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'
  devise_for :users
  
  get 'user/auto_login', to: 'users#auto_login'
  resources :agences 
  resources :buses

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/agence.rb
class Agence < ApplicationRecord
  belongs_to :user
  has_many :buses

  validates :name, presence: true, uniqueness: true
  validates :register_number, presence: true, uniqueness: true
  validates :road, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bus.rb
class Bus < ApplicationRecord
  belongs_to :agence

  validates :name, presence: true
  validates :model, presence: true
  validates :boarding, presence: true
  validates :destination, presence: true
  validates :no_of_seats, presence: true
  validates :time, presence: true
  # validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :agences
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
end

app/controllers/agences_controller.rb
class AgencesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_agence, only: %i[edit update destroy]

  def index
    @user = current_user
    @agence = @user.agences.all
  end

  def show
    @agence = ge_buses
  end

  def new
    @agence = Agence.new
  end

  def create
    @agence = Agence.create(agence_params.merge(user: current_user))
    if @agence.save
      redirect_to root_path, notice: "Agence created successfully"
    else
      redirect_to root_path, alert: "Agence not created"
    end
  end

  def edit; end

  def update
    if @agence.update(agence_params)
      redirect_to agences_path, notice: "Agence updated successfully"
    else
      redirect_to root_path, alert: "Agence not updated"
    end
  end

  def destroy
    @agence.destroy
    redirect_to agences_path, notice: "Agence deleted successfully"
  end

  private

  # get all buses of an agence
  def ge_buses
    @user = Agence.where(user_id: current_user.id)
    @buses = Bus.where(agence_id: @user)
    @agence = Agence.find(params[:id])
  end

  def set_agence
    @agence = Agence.find(params[:id])
  end

  def agence_params
    params.require(:agence).permit(:name, :register_number, :road, :avenue, :contact, :user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :json, :html

  skip_before_action :verify_authenticity_token
  protect_from_forgery with: :null_session
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name phone_number])
  end
end

app/controllers/buses_controller.rb
class BusesController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :set_bus, only: %i[show edit update destroy]

  def index
    @buses = ge_bus
  end

  def show; end

  def new
    @bus = Bus.new
  end

  def create
    @bus = Bus.new(bus_params)
    respond_to do |format|
      if @bus.save
        format.html { redirect_to root_path, notice: 'Bus was successfully created.' }
        format.json { render :show, status: :created, location: @bus }
      else
        format.html { render :new }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @bus.update(bus_params)
        format.html { redirect_to @bus, notice: 'Bus was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus }
      else
        format.html { render :edit }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bus.destroy
    respond_to do |format|
      format.html { redirect_to buses_url, notice: 'Bus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def ge_bus
    @user = User.find(current_user.id)
    @agence = Agence.find(@user.agence_id)
    @buses = @agence.buses
  end

  def set_bus
    @bus = Bus.find(params[:id])
  end

  def bus_params
    params.require(:bus).permit(:name, :model, :boarding, :destination, :no_of_seats, :time, :date, :agence_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @buses = Bus.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: %i[index show edit update destroy]

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def auto_login
    render json: {
      user: current_user
    }
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :active)
  end
end

app/helpers/agences_helper.rb
module AgencesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/agences/_agence_preview.html.erb
<table>
  <thead>
     <tr>
        <th>agence_name &emsp;</th>
        <th>registration_number&emsp;</th>
        <th>road&emsp;</th>
        <th>avenue&emsp;</th> 
        <th>phone&emsp;</th>
     </tr>
  </thead>
    <tbody>
        <% @agence.each do |agence| %>
            <tr>
                <td><%= link_to agence.name, agence_path(agence) %></td>
                <td><%= agence.register_number %></td>
                <td><%= agence.road %></td>
                <td><%= agence.avenue %></td>
                <td><%= agence.contact %></td>
                 
            </tr>
        <% end %>
    <tbody>
</table>

app/views/agences/_form.html.erb
<%= form_with model: @agence do |form| %>
  <div class="field flex flex-col w-1/6 my-1">
    <%= form.label :name, class: "font-bold" %>
    <%= form.text_field :name %>
  </div>

   <div class="field flex flex-col w-1/2 my-2">
    <%= form.label :register_number, class: "font-bold" %>
    <%= form.text_field :register_number %>
  </div>

    <div class="field flex flex-col w-1/2 my-2">
    <%= form.label :road, class: "font-bold" %>
    <%= form.text_field :road %>
  </div>

  <div class="field flex flex-col w-1/2 my-2">
    <%= form.label :avenue, class: "font-bold" %>
    <%= form.text_field :avenue %>
  </div>

     <br/>

  <div class="field flex flex-col w-1/2 my-2">
    <%= form.submit%>
  </div>

<% end %>

app/views/agences/edit.html.erb
<h1>Editing <%= @agence.name %></h1>

<div class="pv4">
  <%= render 'form', agence: @gence %>
</div>

app/views/agences/index.html.erb
<h3>Hello <%= @user.first_name%></h3>

<h1>Your agences</h1>

<div class="w-11/12 md:w-1/2 mx-auto">
  <%= render partial: '/agences/agence_preview' %>
<div>

app/views/agences/new.html.erb
<div class="pv4">
  <%= render 'form', agence: @gence %>
</div>

app/views/agences/show.html.erb
<h1 class="title is-2"><%= @agence.name %></h1>

<section class="section instrument-show">
  <div class="columns">
    <div class="column is-8">     
      <ul class="pv1">
        <% if @agence.register_number? %>
        <li class="inline-block pr3"><%= @agence.register_number %></li>
        <% end %>

        <li class="inline-block pr3"><%= @agence.road %></li>

        <li class="inline-block pr3"><%= @agence.avenue %></li>    
      </ul>
    </div>
 </div>
</section>

<table>
  <thead>
     <tr>
        <th>bus_name &emsp;</th>
        <th>model &emsp;</th>
        <th>boarding&emsp;</th>
        <th>destination&emsp;</th>
        <th>No of Seats&emsp;</th> 
        
         <th>Time&emsp;</th>
        <th>Action</th> 
     </tr>
  </thead>
    <tbody>
    
          <% @buses.each do |bus| %>
              <tr>
                  <td><%=link_to bus.name, bus %></td>
                  <td><%= bus.model %></td>
                  <td><%= bus.boarding %></td>
                  <td><%= bus.destination %></td>
                  <td><%= bus.no_of_seats %></td>  
                  <td><%= bus.time %></td>
              </tr>
          <% end %>
     
    <tbody>
</table>

    <br/>
    <br/>

<%= link_to 'Edit', edit_agence_path(@agence) %>

<%= link_to 'Create bus', new_bus_path %>

app/views/buses/_bus.html.erb
<div id="<%= dom_id bus %>">
  <p>
    <strong>Name:</strong>
    <%= bus.name %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= bus.model %>
  </p>

  <p>
    <strong>Boarding:</strong>
    <%= bus.boarding %>
  </p>

  <p>
    <strong>Destination:</strong>
    <%= bus.destination %>
  </p>

  <p>
    <strong>No of seats:</strong>
    <%= bus.no_of_seats %>
  </p>

  <p>
    <strong>Time:</strong>
    <%= bus.time %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= bus.date %>
  </p>

  <p>
    <strong>Agence:</strong>
    <%= bus.agence_id %>
  </p>

</div>

app/views/buses/_form.html.erb
<%= simple_form_for(@bus) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :model %>
    <%= f.input :boarding %>
    <%= f.input :destination %>
    <%= f.input :no_of_seats %>
    <%= f.input :time %>
    <%= f.input :date %>
   
    <%= f.association :agence%>
  
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/buses/edit.html.erb
<h1>Editing bus</h1>

<%= render "form", bus: @bus %>

<br>

<div>
  <%= link_to "Show this bus", @bus %> |
  <%= link_to "Back to buses", buses_path %>
</div>

app/views/buses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Buses</h1>

<div id="buses">
  <% @buses.each do |bus| %>
    <%= render bus %>
    <p>
      <%= link_to "Show this bus", bus %>
    </p>
  <% end %>
</div>

<%= link_to "New bus", new_bus_path %>

app/views/buses/new.html.erb
<h1>New bus</h1>

<%= render "form", bus: @bus %>

<br>

<div>
  <%= link_to "Back to buses", buses_path %>
</div>

app/views/buses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bus %>

<div>
  <%= link_to "Edit this bus", edit_bus_path(@bus) %> |
  
  <br/>
  <br/>

  <%= button_to "Destroy this bus", @bus, method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<ul class="nav nav-tabs" id="myTab" role="tablist">
   <%= link_to 'Booking', root_path, class: 'navbar-brand' %>

   <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, class: "nav-link", data: { turbo_method: :delete } %></li>
      </li>
         <li class="nav-item">
        <%= link_to 'edit', edit_user_registration_path, class: "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to 'My agences', agences_path, class: "nav-link" %>

    <% else %>
      <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
      </li>
    <% end %>
      <li class="nav-item">
        <%= link_to 'sign up', new_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Create agence', new_agence_path, class: "nav-link" %>
      </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bus_booking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application.bootstrap", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
   
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcom to Bus Booking</h1>




<table>
  <thead>
     <tr>
        <th>bus_name &emsp;</th>
        <th>model &emsp;</th>
        <th>agence &emsp;</th>
        <th>boarding&emsp;</th>
        <th>destination&emsp;</th>
        <th>No of Seats&emsp;</th> 
        
         <th>Time&emsp;</th>
        <th>Action</th> 
     </tr>

  </thead>
    <tbody>
        <% @buses.each do |bus| %>
            <tr>
                <td><%= bus.name %></td>
                <td><%= bus.model %></td>
                <td><%= bus.agence.name %></td>
                <td><%= bus.boarding %></td>
                <td><%= bus.destination %></td>
                <td><%= bus.no_of_seats %></td>
                <td><%= bus.time %></td>
              
            </tr>
        <% end %>
    <tbody>
</table>

app/views/users/_form.html.erb
<h2>Edit</h2>

<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
     <%= f.input :first_name,
                autofocus: true,
                input_html: { autocomplete: "first_name" }%>
       <%= f.input :last_name,
                autofocus: true,
                input_html: { autocomplete: "last_name" }%>
     <%= f.input :phone_number,
                autofocus: true,
                input_html: { autocomplete: "phone_number" }%>
    <%= f.input :email,
                autofocus: true,
                input_html: { autocomplete: "email" }%>
    <%= f.input :password,
                hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                input_html: { autocomplete: "new-password" } %>
    <%= f.input :password_confirmation,
                input_html: { autocomplete: "new-password" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Sign up" %>
  </div>
<% end %>

app/views/users/edit.html..erb
<%= render partial: ",," %>